[[libusb]]
arch = "aarch64"
git-tree-sha1 = "04acd69a8052926b7f5a6f404057a532c3909502"
os = "macos"

    [[libusb.download]]
    sha256 = "2f7fd04b5db4672b04927d56ceb272278c62a1cd20d831cf8f922cbac2e23167"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.aarch64-apple-darwin.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "72b586757cd89a80b5835cc24f609c3ed049d42c"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "21e49f122e7d9e74bbb439e412a7e4975e84568159dbf35d1026afdfce153f7a"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.aarch64-linux-gnu.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "e8e30c8c9e947f7cc2ca1b772ef4c0253f17fb49"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "59cd34d1b3cc850599e187afbcabe2f14d5c3ce505e7a5003175d89296268002"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.aarch64-linux-musl.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1007bbb9f3edc4a75c894fd7e4807c8d7f2975ef"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "313f54f667bfd66f6fff9ea1451b8ffbdbc4644cbc53a1bc6ccdf72b9e8403c3"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.armv6l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bd063ad63882643ae1fb437b6ca7764c174bb34"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "1be70be5f049f8d97e529da65d0f56b71bd161cc276f8013a7da5367dd13d6f9"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.armv6l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63b487e199d01a212f41c6d36ae52b00734db764"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "0b126ff7ea66a8f010b7c4042a5b89de96fa372d94b335aa4a65261981331383"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.armv7l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b62a735a4a16b4354c041ff3811dabd2065afdec"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "2ccbb0635526bbcd654a4a40de4bee925439cd7075bbe2e522931153df365034"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.armv7l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "ea189bfd1d529df877ebea1c613359441b93456a"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "422ed68468b22526435488b5aa888a2804fa693451e2aae0f438bcfffba8fa92"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.i686-linux-gnu.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "46cbee37127b3dfda57f37983ff526974cfc14c5"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "0dfa8ae7cdb9234c8afeea4dd14cfad89be0e54f12ce1f114ba9df3f0481ceee"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.i686-linux-musl.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "c1e807bbb694d70be04a44e6a349f7be0713a8c1"
os = "windows"

    [[libusb.download]]
    sha256 = "89bf45b773aecb73a38bfdea64c663c98c8f1a04fe7ae03792199559bc042e15"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.i686-w64-mingw32.tar.gz"
[[libusb]]
arch = "powerpc64le"
git-tree-sha1 = "54e2e103e2115d067e8739a8e9e3938d8ef375e7"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "04f3bc1f785860e9aa3744ff1c44fc9e3ef71b1f9c8782979ddf0d39cfa4eec7"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.powerpc64le-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "34676c8e894766434c0e5eceaef7d46a25340f7f"
os = "macos"

    [[libusb.download]]
    sha256 = "2db1368375f9b4e6ea4aaa4efdc94a708ead9b94c37b90ac6dde8d792e0401ac"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.x86_64-apple-darwin.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "4d8966b9dedc266b5e54ff9cd0684b464f3ecd0b"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "f265c0bbe2a12f7963108b288a8979baa5c09fbbd4875cb21b57b4bbd7140350"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.x86_64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "9f047fd305259971e7f94b5bb9542470b64a0c8c"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "8940da720b1f785a7368ec1ea2c075d9ca922b3c4ce349d33d34bc2c4443bd62"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.x86_64-linux-musl.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "c8c67f84a2a3df31d989f84bd6d50a8e377c54a9"
os = "windows"

    [[libusb.download]]
    sha256 = "704ac11fc606946d5cfcc687c2d595f84c2a22f0c3513e5516f3cf1ef317899d"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.24+0/libusb.v1.0.24.x86_64-w64-mingw32.tar.gz"
