[[libusb]]
arch = "aarch64"
git-tree-sha1 = "eff96b698c566da25178412bec14944cfeaed5ce"
os = "macos"

    [[libusb.download]]
    sha256 = "71f863677c365ef348ef2b5694a96a1b41f05103b5ecae75c96850125d1016b4"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.aarch64-apple-darwin.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "071febbccbb670cb09f61c27ebadc59d81ef2332"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "3883e61da85996648be922381620e26cd2ded23d580e0f575308e6800b91fd15"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.aarch64-linux-gnu.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "d5436a4df8311ae58acc2bd18ed5101b74bd3f1e"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "7d13fcf197ae70240c3ccd0f9dd2ebbb65b483d42e27353f0dc7d0fb3049f5cd"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.aarch64-linux-musl.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "b57ef12d1a2af17d0ba6f9b968c8278ba4f769f0"
os = "freebsd"

    [[libusb.download]]
    sha256 = "0c274fe040846114baefdb4fa40730b105ebc48b72eb78ed6d8de3356487a046"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.aarch64-unknown-freebsd.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a01430abae3e5386045519d1d9b7c72628d49fc"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "fdb0e3b1124f3fa39027da10a7c60fedfeb8df912aeef70600b7d7f2be8e32b2"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.armv6l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cfde34a98adbf7d7f8c25f3ee6e0b1fa0cf0c593"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "27237623d921f050f916c6819ffddf19350ee3e5447b0c578bd56db9a2e23d6b"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.armv6l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31a0f286d0ce3438de86095bf5e7485d2a210dd3"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "8de55e09706383e6fe3855d60ce015eca5edd449b103a94073b9a59fdcebaa50"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.armv7l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dabdce5f65047153099adfce8abe29ef9257be69"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "2b5de76ab2abb120c1cac10e1e4fd4d32d20a8a6db3d9fcd126eb78836c10d04"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.armv7l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "7635953b9ef86fa2368760ae8f5c289ad1130b3c"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "3eaef3c5a3b3234beed3b35f22e6703c3483e13e73e542d2eeabc95b8218f366"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.i686-linux-gnu.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "8f191ab67d888f4c32b3ac613f1633698a4e2e5e"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "681200dc89e1b8b5101bf6b5f74ed724a2f2c9bb53fd65e7ae6628fbf7ff624f"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.i686-linux-musl.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "ebcf61e996aaa99b1754d927e2a8336e8cc89cca"
os = "windows"

    [[libusb.download]]
    sha256 = "f12baed679fb3f7d7cc083729e57139714e1c0889caefc83da62a1444d97aad8"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.i686-w64-mingw32.tar.gz"
[[libusb]]
arch = "powerpc64le"
git-tree-sha1 = "dbfc85a36004c448bb1bc249575009531954fd37"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "3045ea7c16bb46fa761c89cb12e263d02ca6a554cff0ea586ed34eba9e5ce1c2"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.powerpc64le-linux-gnu.tar.gz"
[[libusb]]
arch = "riscv64"
git-tree-sha1 = "9aa90ac26116f66bee888b4f5421617d63a68a09"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "3da5a2f93c5e29d4e947c63e2edffcfaf7112f75525fec198ec53c4aaa8c6b37"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.riscv64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "6b73d05fdbc2601ba7d3054af174c594f1300b7c"
os = "macos"

    [[libusb.download]]
    sha256 = "64d1e01900e122fc393f46c2c49e5eacc230cd2137ca588b4804d976318b0b3c"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.x86_64-apple-darwin.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "70419c04440d0959581e81cbca24975cc5a58f04"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "70685cc5fb119f434a0a4f42f651fe9375bac50598f4bc4b4b56ba07fc36d429"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.x86_64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "d9068c9949db070d9d1a43179eda0938d49fd4f0"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "1046993553b02d80d9d03fd037fa0341bd76b521967c75c42241b0c07a484ecd"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.x86_64-linux-musl.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "9dd5dd258afc43bbe61c2e99d47d366a3db20acb"
os = "freebsd"

    [[libusb.download]]
    sha256 = "973cdff450ce041425f0f6dcd7c174b643d6fc8a62da22e99c72fd2fcbbc6075"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.x86_64-unknown-freebsd.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "694d116e1e074c762b4725f58ee889150d1b5f5a"
os = "windows"

    [[libusb.download]]
    sha256 = "6ee78b722872a9c4f041b1d66f9186693a60c92693239d2029f4c1584fca07d9"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.29+0/libusb.v1.0.29.x86_64-w64-mingw32.tar.gz"
