[[libusb]]
arch = "aarch64"
git-tree-sha1 = "61823eec87652a452cb62b8b623e4b983c2412ad"
os = "macos"

    [[libusb.download]]
    sha256 = "cadaf1b55d9ca590a8a1bce891a01ef8c20d6042b58bb6a84c661f6397f360df"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.aarch64-apple-darwin.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "8ee76f1b8af8acb6a9a7c630c74dad6aaac7bf35"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "89cbd56ba990651252251ff73559deff0381b57d3f207130168421ed622748b7"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.aarch64-linux-gnu.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "8db9f4500cca16004a8c256f59469a86e9215cfa"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "5a80101a85a5be311e656207952f6dc0b505791836b5e49ad9b2750069cb787b"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.aarch64-linux-musl.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b1a7f764af8530d83c7c154398cc6b7e9325b13"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "c090a77e9c24357dd18a357f5a17e1c9524654001de5a28a7aee73335d6bca52"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.armv6l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "98fb03056379ec148807609a676fcb88298f865a"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "46ee5fb5f65b95018f76d5efa1097bb2b96f5d030fc10d0ab82a88062b2c60e2"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.armv6l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da233f6a58b58029f4762ce2816314338f84cec8"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "502ec87b26f399d4a56bb6c157630fc53b21ca0e031227fe2da67f4366e27bc2"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.armv7l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "071fd14c3a3d901e2cc66195fb8f516e07e7946a"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "25cc5dc4fc302127bdb80c2260f33e9f4d272dfc13d71625d2955280cb81a5e3"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.armv7l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "5d29808c4b53c2de603101318723b559f59b2f9a"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "211240771d13ad24b56b5e2fe710a78a10e39ff1d7cea28404609c5ec3aacabc"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.i686-linux-gnu.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "5fec6ef54eda176801ac200a9a760f08529241bc"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "1e54e8e2e7c3a9f1ad4d54c2a70ac37c9913979d44baa58900674bf381699299"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.i686-linux-musl.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "2d64391c165393e6a62a86ac56e3745411f0e2aa"
os = "windows"

    [[libusb.download]]
    sha256 = "f98a4889c3015d50c3236d462ed0589294ea69ba207168b7fb873f19fee00ddc"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.i686-w64-mingw32.tar.gz"
[[libusb]]
arch = "powerpc64le"
git-tree-sha1 = "625ce00c730a74d33401d22fec895536ad446a76"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "fbb9d08da444038a863e4677c019c476a20e101cae52fd357be8a58422375e7d"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.powerpc64le-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "5088bb5bd498529ac64765cfd8f37d09e7c86cc2"
os = "macos"

    [[libusb.download]]
    sha256 = "ee4e6bdf8f2e48c566e9987ecb67218c0dc17a59f0ae501fce398144e9cefef1"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.x86_64-apple-darwin.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "cd2a66b30b74691d16bc79b98f1af7c963099d6a"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "553ca1206b2983a5762deafa8d68af8df9922fbc5fbe5e1f391b06fae3b5436b"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.x86_64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "848d50664da33b4a8ba34389d878b3989f9695a3"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "93420a2178d797aa821abbce8cefdac6e458ffbe01bb5a4d0970eb312d270d7a"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.x86_64-linux-musl.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "e7489b1ae9376387cbbe135cba292fb7d8eafbca"
os = "freebsd"

    [[libusb.download]]
    sha256 = "e4062f08474067c7f81b05cab833d59f498c2a76ab003dad8cf4052879c06992"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.x86_64-unknown-freebsd.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "313bb0051fc1898d188d094a3fbb1655a3549b0a"
os = "windows"

    [[libusb.download]]
    sha256 = "f76b6cc993363f5b9825f2d43af62d12e29c07027a8db12436dce3f2c3d59329"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+0/libusb.v1.0.27.x86_64-w64-mingw32.tar.gz"
