[[libusb]]
arch = "aarch64"
git-tree-sha1 = "08410f8bd5e5351582c4a338e2a49bc28bfccadd"
os = "macos"

    [[libusb.download]]
    sha256 = "d87591f51562624ad137ad66b91181a9a89c7db19de69748e2d14e2f5cb91f27"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.aarch64-apple-darwin.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "290889a54b33e8aa3f9b5bfb9878836e44c3cd57"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "07064d151323979243752831becd21959b03d0117cfe8ed72b1acc9c4517d162"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.aarch64-linux-gnu.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "084fcd96672a81190ec194ef71535fdaf780b291"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "101f0278cd679b45648f5782e5023893e60c39964865f7852b8ef322df4f2c2f"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.aarch64-linux-musl.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5046b3fd2a1c63fa9d413dec5d05bc294f5183a"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "12cd0917bf3a2aaf4306f8d668d5d03d4960e5dae51c9660fc21c0ede0279b88"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.armv6l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75e893358a7442730d260bbd6cc90cae797a4024"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "22d93dcbe06a6682735fb762735746c291caf971501541fac7d2d64660f3aa86"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.armv6l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec02da0d623f6a55107b6cc3be4ffbca48b0e172"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "1de6345207cfe3957c375614f31acccf5013a8af28b5b8b6954847bef7156df6"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.armv7l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e0ca63a49a9e36c3de288242318448a26982fb8e"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "d820b37224f4135de27a7cf12ab298c8fa0fb41a7233bab44f2d47c7e20901b4"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.armv7l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "57aaa468e4dc1bb34004829cb00cdad278c032db"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "3391d174508996957d3501269a9c14527e48e61977261d9ef1de240d849307c9"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.i686-linux-gnu.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "a9e8799315b90fa78ce6dfebfa13b98ee9491b2a"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "0bb87145af88e425331dce2d712cf5633a9212fd61438bbe2507326062b64ecd"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.i686-linux-musl.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "38b68ac6a226ee89c36cd278e2945289e872ef5f"
os = "windows"

    [[libusb.download]]
    sha256 = "5ad5980370df7490722c1a3ecac0ba59ba27479649817a065f511de0761ba3bf"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.i686-w64-mingw32.tar.gz"
[[libusb]]
arch = "powerpc64le"
git-tree-sha1 = "4efc82495cb646f5bf9c1987b501904dc567bbf5"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "f022ef75bb5d9019af66c18b35178e123424a10452cac04115e64ce18ebe2276"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.powerpc64le-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "6e69adad2801a6e7ef340e1893e0d7cb0fa18c02"
os = "macos"

    [[libusb.download]]
    sha256 = "c709ecc2c36b337f73e851f8729bcb382138f95306da723af1b558a0651d24bb"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.x86_64-apple-darwin.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "3888805a32adaf3439cbd23178b2e9b5e922995c"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "e5f030d0e5b2add5c44aa39d3e298ffaf57edb28d83375f19a97886fb3f1e498"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.x86_64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "11ab010c1d4a42f9ddd59f5f3ab7796747472484"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "fd0c557de22a34b5580a53a7ca63d66d6455a5372ff0b9cc792847c05da64888"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.x86_64-linux-musl.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "83ce7fa0b21734eda6bcb149c8229d50eb678333"
os = "freebsd"

    [[libusb.download]]
    sha256 = "0e5a2e087f281a6d417f2213e02de9af8b34d9ce8ed87f7f1d7cf043345fba12"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.x86_64-unknown-freebsd.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "70c3eda10a18cd5f07fe4b86b4a996e2b272cb23"
os = "windows"

    [[libusb.download]]
    sha256 = "55b21edd319fc168646a999aab14b6a24e4fcd5a2474bfb3f48d061a104efbbd"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.26+0/libusb.v1.0.26.x86_64-w64-mingw32.tar.gz"
