[[libusb]]
arch = "aarch64"
git-tree-sha1 = "b001e172247d4e93dc506338d9669081d1764ab0"
os = "macos"

    [[libusb.download]]
    sha256 = "7cae2ff1c0f104f523a660b39386b8fd4d881f74ce66b70a6577fa318453e7f9"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.aarch64-apple-darwin.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "cab3ea7696a83f58658c9880a8c925a5ff3e47d7"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "f7c756acd103a0b86a162e78d8e2d82de9536089afe6af7449001442216fee87"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.aarch64-linux-gnu.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "ce68520c1729c9581a7be094794b1bbe9f9aa646"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "01fc6737794ad96535f11bfd180a769915deed6f00a506831c49ccd9b7fed61f"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.aarch64-linux-musl.tar.gz"
[[libusb]]
arch = "aarch64"
git-tree-sha1 = "076d3e7966b6824454ca6ce503ee72a515c76112"
os = "freebsd"

    [[libusb.download]]
    sha256 = "03723ec072bef92e0ed63ed755baf3f56c3384b8faefaaa6edfe813f3908825d"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.aarch64-unknown-freebsd.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e601b254692d3cc6458299a0b79a707c771d254"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "87b6d73e9736d07bc068a39be16ea2a09a7fbda98fa08a902e61937af8020932"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.armv6l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b75a9569929e61a563e52bfddb130fbd74e9f077"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "c80be44c977b130834c652a0185e51b5c9127289aa3e2f59c170baf6196caa36"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.armv6l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "350dcc6e3aac0f036423bcfe44ab61d87fb06fdd"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "77d70e0902f95e451ce3d3f79140d79d68c4d979b305ff21ab549b049a9dfd94"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.armv7l-linux-gnueabihf.tar.gz"
[[libusb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e344c812e10ec7819b657b554eb939cd151677e1"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "17b5b00bfa898bb32e8c87fcd9aa4f752ad49481cb36486f11dace2375477c91"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.armv7l-linux-musleabihf.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "67c86a2bf1db924223456eee865adaef635a206a"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "be183cd822ac0d9b1b634a7b9dc001c46061931338df9511af25462e9ea90b94"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.i686-linux-gnu.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "1c21a3b5cd4f101ec6a80b111f1a18c803a7847f"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "efad5dd3f9ad693ef66e7c19ddc9dd0b770f8b6d49d7395610a81cb6af95a97a"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.i686-linux-musl.tar.gz"
[[libusb]]
arch = "i686"
git-tree-sha1 = "a36f024c559ecbfe0f5b0b154346711c0be0e79b"
os = "windows"

    [[libusb.download]]
    sha256 = "6c5d7829294e9d5be63c5e29bcddf12d0bbb60a42aeb24d603f77e2fc6ab29f5"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.i686-w64-mingw32.tar.gz"
[[libusb]]
arch = "powerpc64le"
git-tree-sha1 = "cf0b4ee18633ec62bbc77ccede84a06c0a637f32"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "5bba52c7dd4406991a84734faab68d44abae782104c1b96c462193f3f51cb2ee"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.powerpc64le-linux-gnu.tar.gz"
[[libusb]]
arch = "riscv64"
git-tree-sha1 = "bd0b02ee0056ed167001816dac6aaeb2c4023b31"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "93b0fcdf59620eb611d97618f9adbaf0867dff30ece09488e3878fdf63e64a95"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.riscv64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "444ab3816e0e64bff51a29b59f76aa16ee7026f0"
os = "macos"

    [[libusb.download]]
    sha256 = "23e516178cc0528bd77d1f6c9b947a8946ee85553f9200f1a97716271849c170"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.x86_64-apple-darwin.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "a2d0ba2ad156a1b779a0dfe6872633acea94bc83"
libc = "glibc"
os = "linux"

    [[libusb.download]]
    sha256 = "91dad126139f886047e048cfd67395b908902768fbb1b437d53252f2bc903d98"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.x86_64-linux-gnu.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "9a6b0ca90b03426de3434f14a89c431698a23b59"
libc = "musl"
os = "linux"

    [[libusb.download]]
    sha256 = "7c8ade1b875d35de3eacfe1ef94960f77c0ee448f283ec1517da29de72c3561e"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.x86_64-linux-musl.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "8c061e91d51088490cd0a3cb8a933ff3787f184c"
os = "freebsd"

    [[libusb.download]]
    sha256 = "52611f3685abff75242024dd8fca086b3790e8a3f455d57cb4e9ac0c9e026958"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.x86_64-unknown-freebsd.tar.gz"
[[libusb]]
arch = "x86_64"
git-tree-sha1 = "15043efefb44b0091452d88502e6b164636009c1"
os = "windows"

    [[libusb.download]]
    sha256 = "6b4bbcbb387cf159e1f4bca7d3c44f65004c92d6ae81195f669bfd9ec2f36f4d"
    url = "https://github.com/JuliaBinaryWrappers/libusb_jll.jl/releases/download/libusb-v1.0.27+1/libusb.v1.0.27.x86_64-w64-mingw32.tar.gz"
