# Autogenerated wrapper script for libusb_jll for i686-w64-mingw32
export libusb

JLLWrappers.@generate_wrapper_header("libusb")
JLLWrappers.@declare_library_product(libusb, "libusb-1.0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libusb,
        "bin\\libusb-1.0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
